return {
    sfdx_alias_config = {
        value = '$HOME/.sfdx/alias.json',
        doc = [[
        Location of the `alias.json` file generated by sfdx, containing information about all configured aliases. Used for username autocompletion.
        ]]
    },
    sfdx_executable = {
        value = 'sf',
        doc = [[
        Name of the sf command line executable. Useful if the executable has been aliased to something else, or for the full path if it's not in the $PATH.
        ]]
    },
}
